'''
The code is generated by Chat.openai.com
'''
# %% Import necessary packages
import pandas as pd
from fredapi import Fred

# Define API key and initialize connection to FRED
fred = Fred(api_key='44a1237cc6b4e86c722389c399796015')

# Define series ID for CPI
series_id = 'CPALTT01USM657N'

# Download data for CPI
cpi_data = fred.get_series(series_id)

# Convert data to a Pandas DataFrame
cpi_df = pd.DataFrame({'CPI': cpi_data})

# Print the first 10 rows of the DataFrame
print(cpi_df.head(10))

# %%
